ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER users_service IDENTIFIED BY ciFw0RF6EL;

GRANT CONNECT, RESOURCE TO users_service;

GRANT UNLIMITED TABLESPACE TO users_service;

ALTER SESSION SET CURRENT_SCHEMA=users_service;

CREATE TABLE users(
  id CHAR(36) NOT NULL,
  username VARCHAR2(35) NOT NULL UNIQUE,
  email VARCHAR2(320) NOT NULL UNIQUE,
  password_hash VARCHAR2(128) NOT NULL,
  bio BLOB,
  image VARCHAR2(2048),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);